server:
  port: 8080

spring:
  config:
    import: "optional:configtree:/run/secrets/"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:typespeed_db}
    username: ${DB_USER:typespeed_admin}
    password: ${db_password:${DB_PASSWORD:1234}}